# Generated by Django 5.2.9 on 2025-12-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expediente', '0003_ordenreferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio (ej: 09:00)')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin (ej: 14:00)')),
                ('consultorio', models.CharField(max_length=50, verbose_name='Consultorio Asignado')),
                ('medico', models.ForeignKey(limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('medico', 'dia', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('CONFIRMADA', 'Confirmada/Pagada'), ('CANCELADA', 'Cancelada por Paciente'), ('COMPLETADA', 'Consulta Completada')], default='PENDIENTE', max_length=10)),
                ('tipo_cita', models.CharField(choices=[('MG', 'Medicina General'), ('ESP', 'Especialidad')], max_length=3)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.agenda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expediente.paciente')),
            ],
        ),
    ]
