# Generated by Django 5.2.9 on 2025-12-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
