# Generated by Django 5.2.9 on 2025-12-03 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CURP', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('tipo', models.CharField(choices=[('A', 'Asegurado'), ('N', 'No Asegurado')], default='N', max_length=1, verbose_name='Tipo de Paciente')),
                ('RFC', models.CharField(blank=True, max_length=13, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico (NOM-004)')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento (NOM-004)')),
                ('evolucion', models.TextField(verbose_name='Evolución y Notas (NOM-004)')),
                ('procedimientos', models.TextField(blank=True, null=True, verbose_name='Procedimientos')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(limit_choices_to={'rol__in': ['MEDICO', 'ENFERMERO']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='expediente.paciente')),
            ],
            options={
                'verbose_name_plural': 'Notas de Consulta',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
