# Generated by Django 5.2.9 on 2025-12-03 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.CharField(max_length=255, verbose_name='Diagnóstico')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (m)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('requiere_firma', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(limit_choices_to={'rol__in': ['MEDICO']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255, verbose_name='Medicamento')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentación')),
                ('dosificacion', models.TextField(verbose_name='Dosificación e Indicaciones')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='expediente.recetadigital')),
            ],
        ),
    ]
