# Generated by Django 5.2.9 on 2025-12-03 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_recetadigital_detallemedicamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_solicitada', models.CharField(max_length=100)),
                ('motivo_referencia', models.TextField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Agendar'), ('AGENDADA', 'Cita Agendada')], default='PENDIENTE', max_length=10)),
                ('medico_general', models.ForeignKey(limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Médico General Emisor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.paciente')),
            ],
        ),
    ]
