# --- Etapa 1: Construcción ---
FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# --- Etapa 2: Servir ---
FROM nginx:alpine

# ELIMINAMOS el error 404 de React creando una configuración básica
# Esto le dice a Nginx: "Si no encuentras el archivo, envía todo a index.html"
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]