# Generated by Django 5.2.9 on 2025-12-03 02:32

import personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personal',
            managers=[
                ('objects', personal.models.PersonalManager()),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
